### PR TITLE
make memory view live

### PR DESCRIPTION
**Pull request by johnjiabinzhang**
track memory view docs, when a stop event occurs, update their contents.

### CODE REVIEW

**Comment by Marus** [comment]
I think this all looks good, I’ll give it a final test and include it in the next release.

**Comment by johnjiabinzhang** [comment]
Great!

**Comment by johnjiabinzhang** [comment]
Also, I'm noticing that in `memory_content_provider.ts` line `25` and `46`, it is subtracting `0x08000000` from the line address. Is there any particular reason why? I don' think it should be there.

**Comment by Marus** [comment]
No, it shouldn’t be there. At some point I was experimenting with trying to integrate with the hexdump extension - must have accidentally committed something. I’ll fix that.

**Pull request merged**
