### PR TITLE
Remove svd-viewer

### PR DESCRIPTION
**Pull request by thegecko**
This PR removes the svd-viewer source from Cortex-Debug in favour of using the generic svd-viewer here:

https://github.com/cortex-debug/svd-viewer

https://marketplace.visualstudio.com/items?itemName=cortex-debug.svd-viewer

This allows the svd-viewer to be used by any debugger.

I believe all existing functionality and bug fixes have been transferred to the new repository.

An extension dependency for svd-viewer has been added to this extension, in future this may be better solved using an extension pack.

cc @haneefdm

### CODE REVIEW

**Comment by haneefdm** [comment]
I have not heard from @Marus so, I cannot merge this PR. I sent him an email over the waiting and awaiting a response. I feel right to take his code and do this.

I know it is MIT License and all but we need to wait.

**Comment by haneefdm** [comment]
Hi Rob, I just looked at your repo and the changes you made here, and I have several issues. I fixed some bugs and made some enhancements in the last several months. I see a few made it into your repo but some major ones did not. 

The SVD Viewer now supports multiple debug sessions. That is gone. Also, I use a different strategy for addr-ranges and it did not make it into your version and so did the bug fixes I made while doing that.

I think we need to start over. But please, let us coordinate with @Marus and myself before you make any changes or PRs. I spent the last two hours seeing what happened.

We have backwards compatibility to worry about as well and I couldn't tell what was preserved.

**Comment by thegecko** [comment]
>  I fixed some bugs and made some enhancements in the last several months. I see a few made it into your repo but some major ones did not.

This fork was created ~7 Months ago, so not surprised things slipped through.

> The SVD Viewer now supports multiple debug sessions. That is gone. Also, I use a different strategy for addr-ranges and it did not make it into your version and so did the bug fixes I made while doing that.

Do you have relevant PRs I can see to help catch these?

> I think we need to start over. 

I'll take a look at rebasing this again, there's also fixes and web support added in this fork, so keen to get the best from both worlds.

**Comment by haneefdm** [comment]
Please don't do any work and wait. I have to resolve several issues that have nothing to do with code. I don't want to waste your time.

**Comment by haneefdm** [comment]
I am going to close this. I want to factor SVD out of this repo but not actually remove it from here -- will be disabled. That is above my pay grade. I will do the same thing I did for the memory views and the debug-tracker which are now live.

**Comment by thegecko** [comment]
@haneefdm I see you also created a new organisation for extracted functionality over at [mcu-debug](https://github.com/mcu-debug)

As I also did something similar for the [cortex-debug](https://github.com/cortex-debug) organisation (which I invited you to), it seems we are trying to do the same thing. Shall we converge on one? I don't mind which.

**Comment by haneefdm** [comment]
I was trying to create a plan but you were moving too fast for me. And `cortex-debug` was not the name I wanted and there is also an issue of ownership. I had to work these out with @Marus the owner of this repo and take baby steps. And, @Marus is generally busy, so I had to wait. Disregarding his opinion/feelings was not an option.

I told you I will first start with creating an [extension & npm module](https://github.com/mcu-debug/debug-tracker-vscode) to detect debug events in a consistent/shareable way. That is what I did. We also need to support other debuggers besides cortex-debug and that is the other goal. We also did not want to limit to Cortex devices.

Memory viewer was the first to integrate with the legacy one preserved. Moving RTOS is happening now with two other contributors and two new OSes. Should be finished in a week or so.

All of this is happening but at my pace.

**Comment by thegecko** [comment]
> I was trying to create a plan

It sounds like you already have a plan with the new organisation and the abstracted debug event architecture.

> ...you were moving too fast for me

The extracted svd-viewer was created back in January. The new org was just a proposal as I needed somewhere to put it.

> I told you I will first start with creating an [extension & npm module](https://github.com/mcu-debug/debug-tracker-vscode) to detect debug events in a consistent/shareable way.

Please make this optional to ensure compatibility without dependencies.

> We also need to support other debuggers besides cortex-debug
Any work done on my part already aligns to this. Our use cases don't use cortex-debug and in fact aren't even on the desktop!

I feel like where these items are hosted regardless of architecture/approach is something which can be (and even should be) aligned on first. Simply put, do you want me to transfer this into `mcu-debug` and update it to the latest source in cortex debug?

**Comment by haneefdm** [comment]
> Please make this optional to ensure compatibility without dependencies.

Sure, no one HAS o use it. But why would you want to? If an extension lives in this organization, there is no reason not to use -- I am not maintaining multiple versions of trackers. Which debuggers to track is up to the user of the API and so are all the actions for the events. If there are issues, we should resolve them.

About the SVD work, please wait until I am ready -- RTOS needs to be finished and I have to make a maintenance release on Cortex-Debug for some fixes. And, yes, the SVD extension will use the common tracker. It is important for performance and a consistent reaction to various events.

**Comment by haneefdm** [comment]
I am adding comments to issue #736 for the SVD transfer.

**Pull request closed without merging**
